set fenc=utf-8
set encoding=utf-8
set hidden
set number
set cursorline
set cursorcolumn
set virtualedit=onemore
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest
set hlsearch

set expandtab
retab 4
syntax on
